apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: windows-debug
spec:
  version: {{ .TagName }}
  homepage: https://github.com/jsturtevant/windows-debug
  platforms:
  - selector:
      matchLabels:
        os: darwin
    {{addURIAndSha "https://github.com/jsturtevant/windows-debug/releases/download/{{ .TagName }}/kubectl-windows-debug-{{ .TagName }}.tar.gz" .TagName }}
    bin: kubectl-windows-debug
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/jsturtevant/windows-debug/releases/download/{{ .TagName }}/kubectl-windows-debug-{{ .TagName }}.tar.gz" .TagName }}
    bin: kubectl-windows-debug
  shortDescription:  Windows node access via kubectl
  description: |
      kubectl plugin for launching a Windows pod that will give you access to the specified node
      and provide a few useful utilities for debugging Windows processes.
      Access to the node is provided by a Windows Host Process Containers feature in Kubernetes.

      To use this plugin you will need:
      - kubernetes 1.22+ (with the WindowsHostProcessContainers feature-gate enabled)
      - containerd 1.6+ as the runtime

      By default it uses container image https://github.com/jsturtevant/windows-debug/pkgs/container/windows-debug
      which has some useful utilities for debugging Windows processes pre-installed.
      You can provide your own image by using --image flag.
