ARG OS=ltsc2019
FROM mcr.microsoft.com/windows/servercore:${OS} as installer
WORKDIR /apps
USER ContainerUser
RUN powershell /c "iex ""& {$(irm get.scoop.sh)} -RunAsAdmin"""
RUN scoop install vim@8.2.2824 --global