#!/usr/bin/env bash

# default image
image="ghcr.io/jsturtevant/windows-debug:v0.1.3"

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
  -h|--help)
    echo "Windows node access via kubectl"
    echo " "
    echo "kubectl windows-debug <windows-node-name> [options]"
    echo " "
    echo "options:"
    echo "-h,    --help               Show brief help"
    echo "-i,    --image              use custom image"
    exit 0
    ;;
  -i | --image)
  image="$2"
  shift # past argument
  shift # past value
  ;;
  *)    # unknown option
  POSITIONAL+=("$1") 
  shift # past argument
  ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters
nodename="$1"

echo "Running on node '$nodename' with image '$image'"

# sometime ns default is empty from this command so default if it is
namespace=$(kubectl config view --minify --output 'jsonpath={..namespace}')
if [ -z "$namespace" ]; then namespace="default"; fi;

overrides=$(cat <<-JSON
{
  "spec": {
    "nodeName": "$nodename",
    "nodeSelector": {
      "kubernetes.io/os": "windows"
    },
    "hostNetwork": true,
    "securityContext": {
      "windowsOptions": {
        "hostProcess": true,
        "runAsUserName": "NT AUTHORITY\\\\SYSTEM"
      }
    }
  }
}
JSON
)

kubectl run windows-debug-${RANDOM} \
  -it --rm -n $namespace --image $image \
  --image-pull-policy=Always \
  --restart=Never --overrides "$overrides" \
  --pod-running-timeout=15m0s \
  --command -- powershell
