name: image-cleanup

on:
  schedule:
    - cron:  '4 */23 * * *'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  # use gh cli to delete container images from registry when it is pr event
  clean-up-pr-images:
    runs-on: ubuntu-latest
    steps:
      # delete images
      - name: delete images
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "deleting images that start with 'pr-'"
          images=$(gh api \
            -H "Accept: application/vnd.github+json" \
            /users/jsturtevant/packages/container/debug-installer-cache/versions \
            --jq '.[] | select(.metadata.container.tags | any(startswith("pr-"))) | .id')

          for image in $images; do
            # check if image is older than 20hrs
            image_age=$(gh api \
              -H "Accept: application/vnd.github+json" \
              /users/jsturtevant/packages/container/debug-installer-cache/versions/$image \
              --jq '.updated_at')

            if [[ $(date -d "$image_age" +%s) > $(date -d "24 hours ago" +%s) ]]; then
              echo "image $image isn't old enough, skipping"
              continue
            fi

            echo "deleting image $image"
            # https://github.com/cli/cli/issues/3937
            echo -n | gh api --method DELETE -H "Accept: application/vnd.github+json" /users/jsturtevant/packages/container/debug-installer-cache/versions/$image --input -
          done
