name: image-cleanup

on:
  schedule:
    - cron:  '4 */23 * * *'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  packages: delete

jobs:
  # use gh cli to delete container images from registry when it is pr event
  clean-up-pr-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # delete images
      - name: delete images
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./images/clean-up.sh
