name: release

on:
  push:
    tags:
      - 'v*.*.*'
    branches: 
      - main
    pull_request:
      branches:
        - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' && github.ref_type == 'tag'	}}
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: build package
      run: |
        tar -czvf kubectl-windows-debug-${GITHUB_REF_NAME}.tar.gz LICENSE README.md kubectl-windows-debug
    - name: Release package
      uses: softprops/action-gh-release@v1
      with:
        files: kubectl-windows-debug-${{ github.ref_name }}.tar.gz
    - name: Update new version in krew-index
      uses: rajatjindal/krew-release-bot@v0.0.43
